import React from "react";
import "./style.css";
const data = [
  {
    Number: 1,
    FirstName: "Ivan1",
    LastName: "Ivanov1",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 2,
    FirstName: "Ivan2",
    LastName: "Ivanov2",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 3,
    FirstName: "Ivan3",
    LastName: "Ivanov3",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 4,
    FirstName: "Ivan4",
    LastName: "Ivanov4",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 5,
    FirstName: "Ivan1",
    LastName: "Ivanov1",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 6,
    FirstName: "Ivan2",
    LastName: "Ivanov2",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 7,
    FirstName: "Ivan3",
    LastName: "Ivanov3",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 8,
    FirstName: "Ivan4",
    LastName: "Ivanov4",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 9,
    FirstName: "Ivan1",
    LastName: "Ivanov1",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 10,
    FirstName: "Ivan2",
    LastName: "Ivanov2",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 11,
    FirstName: "Ivan3",
    LastName: "Ivanov3",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 12,
    FirstName: "Ivan4",
    LastName: "Ivanov4",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 13,
    FirstName: "Ivan1",
    LastName: "Ivanov1",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 14,
    FirstName: "Ivan2",
    LastName: "Ivanov2",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 15,
    FirstName: "Ivan3",
    LastName: "Ivanov3",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 16,
    FirstName: "Ivan4",
    LastName: "Ivanov4",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 1,
    FirstName: "Ivan1",
    LastName: "Ivanov1",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 2,
    FirstName: "Ivan2",
    LastName: "Ivanov2",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 3,
    FirstName: "Ivan3",
    LastName: "Ivanov3",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 4,
    FirstName: "Ivan4",
    LastName: "Ivanov4",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 1,
    FirstName: "Ivan1",
    LastName: "Ivanov1",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 2,
    FirstName: "Ivan2",
    LastName: "Ivanov2",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 3,
    FirstName: "Ivan3",
    LastName: "Ivanov3",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 4,
    FirstName: "Ivan4",
    LastName: "Ivanov4",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 1,
    FirstName: "Ivan1",
    LastName: "Ivanov1",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 2,
    FirstName: "Ivan2",
    LastName: "Ivanov2",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 3,
    FirstName: "Ivan3",
    LastName: "Ivanov3",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 4,
    FirstName: "Ivan4",
    LastName: "Ivanov4",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 1,
    FirstName: "Ivan1",
    LastName: "Ivanov1",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 2,
    FirstName: "Ivan2",
    LastName: "Ivanov2",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 3,
    FirstName: "Ivan3",
    LastName: "Ivanov3",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 4,
    FirstName: "Ivan4",
    LastName: "Ivanov4",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 1,
    FirstName: "Ivan1",
    LastName: "Ivanov1",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 2,
    FirstName: "Ivan2",
    LastName: "Ivanov2",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 3,
    FirstName: "Ivan3",
    LastName: "Ivanov3",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 4,
    FirstName: "Ivan4",
    LastName: "Ivanov4",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 1,
    FirstName: "Ivan1",
    LastName: "Ivanov1",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 2,
    FirstName: "Ivan2",
    LastName: "Ivanov2",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 3,
    FirstName: "Ivan3",
    LastName: "Ivanov3",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 4,
    FirstName: "Ivan4",
    LastName: "Ivanov4",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 1,
    FirstName: "Ivan1",
    LastName: "Ivanov1",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 2,
    FirstName: "Ivan2",
    LastName: "Ivanov2",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 3,
    FirstName: "Ivan3",
    LastName: "Ivanov3",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
  {
    Number: 4,
    FirstName: "Ivan4",
    LastName: "Ivanov4",
    Gender: "man",
    Email: "123@mail.ru",
    Action: "редактировать",
  },
];
export default function Item() {
  return (
    <>
      {data.map((item, index) => (
        <tr key={index} className="item">
          <td>{item.Number}</td>
          <td>{item.LastName}</td>
          <td>{item.FirstName}</td>
          <td>{item.Gender}</td>
          <td>{item.Email}</td>
          <td>
            <button className="item-btn">{item.Action}</button>
          </td>
        </tr>
      ))}
    </>
  );
}
